### ISSUE TITLE
facebook api კონფიგურაცია

### ISSUE THREAD

**Issue by oalkhanishvili** [oalkhanishvili/Graphite-Front#27]
facebook api კონფიგურაციაsecret key და app key ჩასმა სისტემისთვის

**Comment by ghost** [comment]
itogshi maq eg yvelaferi mara romeli sdk gamoviyenot eg mitxari shen da gavaketeb an linki damide me 4.0 vnaxe mara eg dzvelia rogorts vitsi 5.0 gamovida @oalkhanishvili

**Comment by oalkhanishvili** [comment]
უკვე გავაკეთეა ეს

**Comment by ghost** [comment]
xo mets gavakete 4.0ze ogond

**Comment by oalkhanishvili** [comment]
მანახე მერე რო მოხვალ

**Comment by oalkhanishvili** [comment]
არ dapusho შენ მანახე ჯერ

**Comment by ghost** [comment]
dges ver moval da xval shevikribot

**Comment by ghost** [comment]
shen romeli sdk gaakete ?

**Comment by oalkhanishvili** [comment]
არ ვიცი კოდიგნაიტერის ბიბლიოთეკა ჩავსვი პირდაპირ.შევადაროთ მერე

**Comment by ghost** [comment]
xo mand sessiebs gaukete konfigi ? me sessiebis configi ar gamiketebia tu gaakete atvirte barem da shevadareb me

**Comment by oalkhanishvili** [comment]
სესიას თვითნ აკეთებს არაფრის შეცვლა არ უნდა

**Comment by ghost** [comment]
okay  dapushe mere aba
