### ISSUE TITLE
ბაზაში ახალი ველის გაკეთება

### ISSUE THREAD

**Issue by oalkhanishvili** [oalkhanishvili/Graphite-Front#28]
ბაზაში table user-ში უნდა გაკეთდეს ახალი ველი fb_id სადაც შეინახება fb უზერის უნიკალური id

**Comment by ghost** [comment]
gaketebulia

**Comment by oalkhanishvili** [comment]
გავაკეთე ესენი

**Comment by ghost** [comment]
gaketebuli iyo :D fb id bazashi

**Comment by oalkhanishvili** [comment]
int 11 იყო და არ ამახსოვრებდა ძაან მაწვალა გადავაკეთე text-ად გრძელი კოდია

**Comment by ghost** [comment]
okay
